### PR TITLE
Eliminate Sentry Nomenclature

### PR DESCRIPTION
**Pull request by whalesalad**
- Transition away from `sentry` specific logic to generic `error_handler` function
- Add some very rudimentary docs to README on how this works

### CODE REVIEW

**Review by jimrollenhagen — APPROVED** [review]
LGTM, thanks!

I think ideally we'd have a default error handler that calls `logging.error` or something, but that can be added later.

**Comment by jimrollenhagen** [comment]
Oh, this makes me realize we should pin planner to a specific commit, as this one is a breaking API change. I'll do that real quick, let's wait to merge it.

**Comment by whalesalad** [comment]
I have the changes in my local already (pip installed with the -e flag for local dev) but it doesn't hurt.

EDIT I realize you said planner, my bad.

**Comment by jimrollenhagen** [comment]
planner, not grain-marketing :) though we should do the same in grain-marketing soon.

**Comment by jimrollenhagen** [comment]
Need to merge this first: https://github.com/FarmLogs/crop-planner/pull/202

**Comment by jimrollenhagen** [comment]
Alright, we're good to go now. :shipit:

**Pull request merged**
